### STAGE 1: Build ###
FROM node:16-alpine3.14 as builder

USER root
RUN mkdir -p /opt/nestjsapi/
WORKDIR /opt/nestjsapi/

ENV NODE_ENV build

COPY . .

RUN npm i -g npm
RUN npm install
RUN npm install webpack
RUN npm run build
RUN npm prune --production

### STAGE 2: Run ###
FROM node:16-alpine3.14 as nestjsapi

ENV NODE_ENV production

USER root

RUN mkdir -p /opt/nestjsapi/

WORKDIR /opt/nestjsapi/

COPY --from=builder /opt/nestjsapi/.env .
COPY --from=builder /opt/nestjsapi/package*.json .
COPY --from=builder /opt/nestjsapi/node_modules/ ./node_modules/
COPY --from=builder /opt/nestjsapi/dist/ ./dist/

CMD ["node", "dist/main.js"]
