#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

AFFECTED=$(yarn -s nx affected:apps --plain | sed "s#\s#,#g")

if [ AFFECTED ]; then
  yarn nx run-many --target=lint --projects="${AFFECTED}"
else
  yarn nx run-many --target=lint --all
fi

